# Generated by Django 4.2.3 on 2023-08-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('сan_change_desc', 'can change description'), ('сan_change_category', 'can change category'), ('сan_change_is_published', 'can change is_published'), ('сan_view_price', 'can view price')), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Статус публикации'),
        ),
    ]
