# Generated by Django 4.2.3 on 2023-08-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_options_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('сan_change_desc', 'can change description'), ('сan_change_category', 'can change category'), ('сan_change_is_published', 'can change is_published'), ('сan_view_price', 'can view price')), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
